### ISSUE TITLE
show patch notes after an update

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/slippi-launcher#132]
Patch notes are already listed in the news section (#129), but adding a modal to bring the notes front and center after an update is still important so that people don't accidentally miss what changed in an update.
- [ ] Display a modal that has all the patch notes for each update
  * This may require showing multiple modals or combining the patch notes.

**Comment by Dgarc359** [comment]
I'm taking a stab at this

**Comment by vinceau** [comment]
Not really needed anymore.

**Comment by vinceau** [comment]
Not really needed anymore.
