### ISSUE TITLE
Replays don't launch on Linux

### ISSUE THREAD

**Issue by twiclo** [project-slippi/slippi-launcher#234]
When trying to launch a replay it just starts dolphin. Nothing is outputted to the console

**Comment by NikhilNarayana** [comment]
Please use our discord for support questions (slippi.gg/discord).

**Comment by twiclo** [comment]
How is this a support question? The software is broken. When I ask on discord I either get no response or "Gee man that's weird. Dunno"

**Comment by NikhilNarayana** [comment]
> How is this a support question? The software is broken. When I ask on discord I either get no response or "Gee man that's weird. Dunno"

Replay playback is basic functionality and is definitely not broken, something about your setup is the issue.

Again, please ask in the appropriate support channel so we can solve the issue.

**Comment by krisc** [comment]
at least for me, the linux browser doesn't automically launch Dolphin and play the replay like in Windows. It launches Dolphin and plays the replay after I pick an .iso
