### ISSUE TITLE
bug: Slippi AppImages don't work on glib > 2.68

### ISSUE THREAD

**Issue by baku-dev** [project-slippi/slippi-launcher#239]
Hi,

I have recently upgraded my Debian testing on my workstation and am running glib 2.70 (libglib2.0-0:2.70.0-1+b1). Slippi launcher fails to recognize the already installed AppImages from Netplay and Playback (which do not work using glib 2.70 anyway).

My laptop which is also on Debian testing but running glib 2.68 doesn't run into this issue. It looks like [other AppImages suffer the same issue](https://discuss.getsol.us/d/7339-appimage-stopped-working/2).

Please let me know if you need more information or if I can help in any way.

**Comment by Hnasar** [comment]
I also had this problem when I updated to Fedora 35, which was just released. After poking around, I realized that I could launch the AppImage with: 
```
LD_LIBRARY_PATH=/lib64 ~/.config/Slippi\ Launcher/netplay/Slippi_Online-x86_64.AppImage
```

**Comment by NikhilNarayana** [comment]
This is fixed as mentioned in https://github.com/project-slippi/Ishiiruka/issues/323.
