### ISSUE TITLE
Broadcast list can show an out of date display name

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/slippi-launcher#298]
Minor bug where the broadcast list doesn't have the user's latest display name

## Repro Steps
1. Open the Launcher
2. Change your display name
3. Start Netplay Dolphin
4. Start broadcast to self
5. Refresh broadcast list
6. Notice that the display name doesn't match

![image](https://user-images.githubusercontent.com/6331403/159198832-52fd36cf-48a3-41ac-9c7a-fef051f21726.png)

**Comment by vinceau** [comment]
I feel like this is likely a Slippi backend server issue and not a Launcher issue, since we fetch the broadcasting information from the server and only pass in the connect code as the name.

**Comment by vinceau** [comment]
Closing this as it's not a launcher issue per se.
