### ISSUE TITLE
no /etc/udev/rules.d/51-gcadapter.rules directory after installation

### ISSUE THREAD

**Issue by cosg2002** [project-slippi/slippi-launcher#323]
running Linux Pop!_OS and my gamecube controller adapter is not being detected. i followed the FAQ and ran the command there, but I just now realized I do not even have this directory: "/etc/udev/rules.d/51-gcadapter.rules" . I don't have "51-gcadapter.rules"; the command gives no output. Any help is appreciated.

**Comment by NikhilNarayana** [comment]
please use our discord for support questions.

https://slippi.gg/discord
