### ISSUE TITLE
Display Dolphin versions in launcher

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/slippi-launcher#336]
Would be helpful for easily telling what is installed rather than having to boot dolphin to check.

**Comment by beaudrychase** [comment]
Hello
I was thinking of picking this up as my first issue in this project, and I wanted to get an opinion on where we want this info shown.
I was thinking it would be good to add the info to the sidebar in settings.
![Capture](https://user-images.githubusercontent.com/9560811/199562335-f890ea82-f516-460f-a459-a310fdbbaca1.PNG)

**Comment by zaderrr** [comment]
Had a brief go and put the version at the top.
![Capture](https://user-images.githubusercontent.com/56570635/201894828-f072796f-1c3e-40be-9fcd-69b39784c9d4.PNG)
Not sure where would be better?

**Comment by vinceau** [comment]
Fixed in #351
