### ISSUE TITLE
SlippiReplayDir & SlippiReplayMonthFolders settings are reset to default when Play button launches Dolphin

### ISSUE THREAD

**Issue by vflorelle** [project-slippi/slippi-launcher#337]
Tested on [slippi-launcher](https://github.com/project-slippi/slippi-launcher) 2.5.4 with [Ishiiruka](https://github.com/project-slippi/Ishiiruka) 2.5.1

**Comment by NikhilNarayana** [comment]
![image](https://user-images.githubusercontent.com/6331403/188177316-cb28b931-d90c-4886-b240-d5106edd2965.png)
the launcher manages and enforces said settings based on what you set here.

**Comment by vflorelle** [comment]
It seems I missed this option. It works, thank you.
