### ISSUE TITLE
Extra SLP directories with substring of root directory can't be added

### ISSUE THREAD

**Issue by NikhilNarayana** [project-slippi/slippi-launcher#359]
Attempting to add an adjacent directory that contains the root directory path a substring will result in `Cannot add sub directories of the Root SLP Directory.` error. Users should be able to add these directories since there isn't a real conflict.

Example:
Root = `C:\Users\Nikki\Documents\Slippi`
Adding `C:\Users\Nikki\Documents\Slippi Test` will result in the error mentioned above.

**Comment by dryu99** [comment]
Hey I can take this on! I've already whipped up a local branch, just need collaborator permissions for the repo to push to a remote branch and then I'll make a PR 👍 

```
ERROR: Permission to project-slippi/slippi-launcher.git denied to dryu99.
```
