### ISSUE TITLE
Using mouse back/forward buttons changes window title to 'index.html'

### ISSUE THREAD

**Issue by tec27** [project-slippi/slippi-launcher#366]
Steps to repro:
1) Click any of the top tabs (e.g. Replays)
2) Press back button on mouse

Expected: title of the window remains "Slippi Launcher"
Actual: title becomes "index.html"

**Comment by vinceau** [comment]
I don't have a mouse with buttons to test this, can you please provide a screen recording?

**Comment by NikhilNarayana** [comment]
Here is the issue in action
https://user-images.githubusercontent.com/6331403/210120333-3ab95961-0d72-4407-bf9b-625b5c38c2c2.mp4
