### ISSUE TITLE
Dolphin fails to launch on NixOS

### ISSUE THREAD

**Issue by Noodlez1232** [project-slippi/slippi-launcher#404]
NixOS has a problem running AppImages. They need to be run with the wrapper `appimage-run`. This works to launch slippi-launcher, but any apps that slippi-launcher tries to run fails (Since these AppImages are not run with `appimage-run`.
A proposed solution is to detect when we're running on NixOS, and run `appimage-run` on the application instead of launching directly.

If this can be fixed, I can package the launcher for NixOS, and have it available to those users easier.

I'm willing to work on this, but I don't know how Electron works at all. I do know a bit of JS, but I have no clue where in the code the dolphin appimages are actually being launched.

**Comment by vinceau** [comment]
> I have no clue where in the code the dolphin appimages are actually being launched

This would be a start. https://github.com/project-slippi/slippi-launcher/blob/main/src/dolphin/instance.ts#L40

**Comment by lleheny0** [comment]
@Noodlez1232 Were you able to find a workaround for getting Slippi's Dolphin running in the meantime?

**Comment by Noodlez1232** [comment]
> Were you able to find a workaround for getting Slippi's Dolphin running in the meantime?

Yeah as of right now I use distrobox, and run it inside an Arch container. I had started work on this, but since it's an Electron app, it's been very difficult to get it not just packaged, but even just get a development environment up and running.

**Comment by lleheny0** [comment]
@Noodlez1232 Gotcha, I don't know if you've seen [this](https://github.com/djanatyn/ssbm-nix) yet, but it looks like people are getting it working somehow? I can't really tell. I'm also a Nix noob so I have no idea what to do to get whatever they've got going on there onto my system

**Comment by Noodlez1232** [comment]
Closing, since the [slippi-nix](/lytedev/slippi-nix) repo seems to fix this.
