### ISSUE TITLE
Add SHA hash in plaintext to .yml 

### ISSUE THREAD

**Issue by shashankbangalore** [project-slippi/slippi-launcher#446]
Hi, I was wondering if the SHA512 hashes could be added as plaintext to the .yml files as it seems like they are encoded in some unspecified encoding (base64?). Thanks!

**Comment by NikhilNarayana** [comment]
what hashes are you referring to?

**Comment by NikhilNarayana** [comment]
if you're referring to the ones in the `latest*.yml`, those are created by the build process. not sure what you're expecting out of those, but i don't think they're meant to be in plain text

**Comment by shashankbangalore** [comment]
> if you're referring to the ones in the `latest*.yml`, those are created by the build process. not sure what you're expecting out of those, but i don't think they're meant to be in plain text

Yes, I was referring to those hashes. Do you know what encoding they are in? I cannot find the correct one to decode it to plain text.

**Comment by NikhilNarayana** [comment]
it seems to be double encoded, sha512 -> binary -> base64. i would check the electron builder documentation if you need more info
